management:
  security:
    enabled: false

security:
  basic:
    enabled: false

# eureka:
#   client:
#     healthcheck:
#       enabled: true
#     serviceUrl:
#       defaultZone: http://localhost:8761/eureka/
#   instance:
#     preferIpAddress: false
#     hostname: localhost
