logging:
  level:
    io:
      pivotal: INFO
    com:
      netflix: INFO
    org:
      springframework:
        retry: INFO
        cloud:
          sleuth: INFO

spring:
  cloud:
    loadbalancer:
      retry: true
  zipkin:
    sender:
      type: rabbit

fortune-service:
  ribbon:
    clientTimeoutEnabled: false
    ConnectTimeout: 100
    ReadTimeout: 1000
    MaxAutoRetries: 0
    MaxAutoRetriesNextServer: 0
    ServerListRefreshInterval: 2000

greeting:
  toggles:
    fortuneEnabled: true
  failure:
    latency: 10

hystrix:
  command:
    sayHelloCmd:
      execution:
        isolation:
          strategy: THREAD
          # strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 2000
            interruptOnTimeout: true
            interruptOnCancel: false
        # semaphore:
          # maxConcurrentRequests: 150
        timeout:
          enabled: true
      fallback:
        isolation:
          semaphore:
            maxConcurrentRequests: 150
        enabled: true
      circuitBreaker:
        enabled: true
        requestVolumeThreshold: 20
        sleepWindowInMilliseconds: 5000
        errorThresholdPercentage: 50
        forceOpen: false
        forceClosed: false
      metrics:
        rollingStats:
          timeInMilliseconds: 10000
          numBuckets: 10
        rollingPercentile:
          enabled: true
          timeInMilliseconds: 60000
          numBuckets: 6
          bucketSize: 100
        healthSnapshot:
          intervalInMilliseconds: 500

    backupSayHelloCmd:
      execution:
        isolation:
          strategy: SEMAPHORE
        semaphore:
          maxConcurrentRequests: 20
      fallback:
        enabled: false
      circuitBreaker:
        enabled: false
        requestVolumeThreshold: 20
        sleepWindowInMilliseconds: 5000
        errorThresholdPercentage: 50
        forceOpen: false
        forceClosed: false
      metrics:
        rollingStats:
          timeInMilliseconds: 10000
          numBuckets: 10
        rollingPercentile:
          enabled: true
          timeInMilliseconds: 60000
          numBuckets: 6
          bucketSize: 100
        healthSnapshot:
          intervalInMilliseconds: 500

    falloutSayHelloCmd:
      execution:
        isolation:
          strategy: SEMAPHORE
        semaphore:
          maxConcurrentRequests: 20
      fallback:
        enabled: false
      circuitBreaker:
        enabled: true
        requestVolumeThreshold: 20
        sleepWindowInMilliseconds: 5000
        errorThresholdPercentage: 50
        forceOpen: false
        forceClosed: false
      metrics:
        rollingStats:
          timeInMilliseconds: 10000
          numBuckets: 10
        rollingPercentile:
          enabled: true
          timeInMilliseconds: 60000
          numBuckets: 6
          bucketSize: 100
        healthSnapshot:
          intervalInMilliseconds: 500

  threadpool:
    sayHelloThreadPool:
      coreSize: 10
      maximumSize: 10 # Will be core size unless `allowMaximumSizeToDivergeFromCoreSize` true
      allowMaximumSizeToDivergeFromCoreSize: false
      maxQueueSize: -1 # Requires restart
      queueSizeRejectionThreshold: 5
      keepAliveTimeMinutes: 1
      metrics:
        rollingStats:
          timeInMilliseconds: 10000
          numBuckets: 10
